// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83VXKRQV31nSzZhfP_uH1OgYae6iD_-U',
    appId: '1:628938091989:web:b91a5435af48d95422a15c',
    messagingSenderId: '628938091989',
    projectId: 'rojnivis',
    authDomain: 'rojnivis.firebaseapp.com',
    storageBucket: 'rojnivis.firebasestorage.app',
    measurementId: 'G-QHH4ZZ6T9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvA3xQnB7-bBuooJmCT7TY9nd8UqTURrE',
    appId: '1:628938091989:android:5aec0736cd9d78c922a15c',
    messagingSenderId: '628938091989',
    projectId: 'rojnivis',
    storageBucket: 'rojnivis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNHIa4xtGiW0zcqzO1xTY565duFawSyjU',
    appId: '1:628938091989:ios:5486a442b792f87622a15c',
    messagingSenderId: '628938091989',
    projectId: 'rojnivis',
    storageBucket: 'rojnivis.firebasestorage.app',
    iosBundleId: 'com.rojnivis.rojnivis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNHIa4xtGiW0zcqzO1xTY565duFawSyjU',
    appId: '1:628938091989:ios:5486a442b792f87622a15c',
    messagingSenderId: '628938091989',
    projectId: 'rojnivis',
    storageBucket: 'rojnivis.firebasestorage.app',
    iosBundleId: 'com.rojnivis.rojnivis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB83VXKRQV31nSzZhfP_uH1OgYae6iD_-U',
    appId: '1:628938091989:web:1695fe7f3118440622a15c',
    messagingSenderId: '628938091989',
    projectId: 'rojnivis',
    authDomain: 'rojnivis.firebaseapp.com',
    storageBucket: 'rojnivis.firebasestorage.app',
    measurementId: 'G-42V181LPB3',
  );
}
